apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dhakacart
  labels:
    app: dhakacart-backend
spec:
  type: ClusterIP
  selector:
    app: dhakacart-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
